Add to test: Verify processed files exist

diff --git a/.github/workflows/dandi_testing.yml b/.github/workflows/dandi_testing.yml
--- a/.github/workflows/dandi_testing.yml
+++ b/.github/workflows/dandi_testing.yml
@@ -31,3 +31,8 @@ jobs:
       run: |
         brainsets config --raw data/raw --processed data/processed
         brainsets prepare pei_pandarinath_nlb_2021 -v
+    - name: Verify existence of processed files
+      run: |
+        test -d data/processed/pei_pandarinath_nlb_2021 || (echo "pei_pandarinath_nlb_2021 not found" && exit 1)
+        test -f data/processed/pei_pandarinath_nlb_2021/jenkins.h5 || (echo "jenkins.h5 not found" && exit 1)
+        test -f data/processed/pei_pandarinath_nlb_2021/manifest.txt || (echo "manifest.txt not found" && exit 1)
